name: MacOS_vcpkg

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Install sdl and glfw via vcpkg # Note: Github CI provides a preinstallev vcpkg at /usr/local/share/vcpkg
      run: vcpkg install glfw3 sdl2

#    - name: Setup interactive tmate session
#      uses: mxschmitt/action-tmate@v3

    - name: Configure
      run: |
          mkdir build
          cd build
          cmake \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_TOOLCHAIN_FILE=/usr/local/share/vcpkg/scripts/buildsystems/vcpkg.cmake \
                -DHELLOIMGUI_USE_SDL2=ON         \
                -DHELLOIMGUI_USE_GLFW3=ON        \
                -DHELLOIMGUI_HAS_OPENGL3=ON      \
                -DHELLOIMGUI_USE_GLAD=ON         \
                -DHELLOIMGUI_BUILD_DOCS=ON       \
                ..
    - name: Build
      working-directory: build
      run: |
          make
